version: 2.1 # use CircleCI 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.17.0

jobs: # a collection of steps
  test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "backend/package-lock.json" }}
      - run: cd backend && npm install
      - run:
          name: compile
          command: cd backend && npm run compile
      - run:
          name: npm install frontend
          command: cd backend && npm run vue:prep
      - run:
          name: copy frontend resources
          command: cd backend && npm run vue:cp
      - run:
          name: test frontend 
          command: cd frontend && npm run test
      - run:
          name: test backend 
          command: cd backend && npm run test
      - run:
          name: package 
          command: cd backend && npm run package
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "backend/package-lock.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: test-results.xml
          prefix: tests
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      # - run:
      #     name: Publish package
      #     command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
